server:
  port: 8082

spring:
  application:
    name: payment-microservice


  config:
    import:
      - "classpath:secrets.yml"

  kafka:

    producer:
      bootstrap-servers:
        - localhost:9092
        - localhost:9094
        - localhost:9096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


